### PR TITLE
Fix linter-specific ignore for excluded vars (#2770)

### LINKED ISSUE #2770: #_{:clj-kondo/ignore} suppresses unrelated linters
- [x] I have read the [Clojure etiquette](https://clojure.org/community/etiquette) and will respect it when communicating on this platform.

**version**

clj-kondo v2026.01.19

**platform**

JVM (also reproducible with native)

**editor**

N/A (reproduced from CLI)

**problem**

`#_{:clj-kondo/ignore [:specific-linter]}` on vars inside `:refer-clojure :exclude` suppresses all linters instead of only the listed ones. The `:unused-excluded-var` and `:unresolved-excluded-var` linters are incorrectly silenced even when they are not in the ignore list.

**repro**

```bash
❯ echo '(ns foo (:refer-clojure :exclude [comp]))' | clj-kondo --lint -
<stdin>:1:35: info: Unused excluded var: comp
linting took 36ms, errors: 0, warnings: 0

❯ echo '(ns foo (:refer-clojure :exclude [#_:clj-kondo/ignore comp]))' | clj-kondo --lint -
linting took 6ms, errors: 0, warnings: 0

❯ echo '(ns foo (:refer-clojure :exclude [#_{:clj-kondo/ignore [:invalid-arity]} comp]))' | clj-kondo --lint -
linting took 10ms, errors: 0, warnings: 0
```

The third command should still warn about `comp` being an unused excluded var. The ignore only lists `:invalid-arity`, not `:unused-excluded-var`.

**expected behavior**

`#_{:clj-kondo/ignore [:invalid-arity]}` should only suppress `:invalid-arity` findings. Unrelated linters like `:unused-excluded-var` and `:unresolved-excluded-var` should still fire.

I'm interested in doing a PR for this.

### PR DESCRIPTION
**Pull request by jramosg**
Linter-specific ignore metadata (e.g., `#_{:clj-kondo/ignore [:invalid-arity]}`) now correctly respects the specified linters instead of suppressing all linters.

Previously, `utils/ignored?` would short-circuit and suppress all findings when any :clj-kondo/ignore metadata was present, preventing the proper linter-type-aware check in findings/ignored? from executing.

Changes:
- Modified utils/ignored? to accept optional linter parameter and check if the specific linter type matches the ignore metadata
- Updated call sites in linters.clj and analyzer/namespace.clj to pass linter types
- Added tests verifying linter-specific ignore behavior for :unused-excluded-var and :unresolved-excluded-var

Fixes #2770

Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [Clojure etiquette](https://clojure.org/community/etiquette) and will respect it when communicating on this platform.

- [x] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

File: src/clj_kondo/impl/utils.clj [hunk 1]
```diff
@@ -518,8 +518,12 @@
            :name var})
         (:callstack ctx)))
 
-(defn ignored? [expr]
-  (:clj-kondo/ignore (meta expr)))
+(defn ignored? [expr linter]
+  (when-let [{:keys [linters]} (:clj-kondo/ignore (meta expr))]
+    (or (identical? :all linters)
+        (some #(identical? linter (:k %)) linters)
```
Comment (borkdude) [inline src/clj_kondo/impl/utils.clj]: The order seems to cause a bit of unnecessary work here. You can check of linters has `:linters`. if ti has them, it doesn't make sense to run the second or

File: src/clj_kondo/impl/utils.clj [hunk 2]
```diff
@@ -518,8 +518,11 @@
            :name var})
         (:callstack ctx)))
 
-(defn ignored? [expr]
-  (:clj-kondo/ignore (meta expr)))
+(defn ignored? [expr linter]
+  (when-let [{:keys [linters]} (:clj-kondo/ignore (meta expr))]
+    (or (identical? :all linters)
+        (some #(identical? linter (:k %)) (:children linters))
```
Comment (borkdude) [inline src/clj_kondo/impl/utils.clj]: Why did you remove the when-let?

What's the reason that ignored? can receive both nodes and literal expressions?

Comment (jramosg) [reply src/clj_kondo/impl/utils.clj]: ignored receives expressions, the difference is inside `:clj-kondo/ignore` meta

node with `children` appears with linter specific comment
```shell
echo '(ns foo (:refer-clojure :exclude [#_{:clj-kondo/ignore [:invalid-arity]} comp]))' | clojure -M:clj-kondo/dev --lint -

"(meta expr) " {:row 1, :col 74, :end-row 1, :end-col 78, :clj-kondo/ignore {:row 1, :col 37, :end-row 1, :end-col 73, :linters <vector: [:invalid-arity]>}, :clj-kondo/ignore-id :G__17293}
<stdin>:1:74: info: Unused excluded var: comp
linting took 52ms, errors: 0, warnings: 0
```

`:all` for not specific ignores:

```shell
echo '(ns foo (:refer-clojure :exclude [#_:clj-kondo/ignore comp]))' | clojure -M:clj-kondo/dev --lint -

"(meta expr) " {:row 1, :col 55, :end-row 1, :end-col 59, :clj-kondo/ignore {:row 1, :col 37, :end-row 1, :end-col 54, :linters :all}, :clj-kondo/ignore-id :all}
linting took 54ms, errors: 0, warnings: 0
```

And the one I was missing, for disabling with inline metadata. This is now checked with `(some #(identical? linter %) ignore)`
```shell
 echo '(ns foo (:refer-clojure :exclude [^{:clj-kondo/ignore [:invalid-arity]} comp]))' | clojure -M:clj-kondo/dev --lint -

"(meta expr) " {:row 1, :col 73, :end-row 1, :end-col 77, :clj-kondo/ignore [:invalid-arity]}
<stdin>:1:73: info: Unused excluded var: comp
linting took 71ms, errors: 0, warnings: 0
```
