### PR TITLE
#1755: Fix mapcat transducer invalid-arity false positives

### LINKED ISSUE #1755: Calls to mapcat transducer in sequence report invalid arity with multiple collections
There was a wonderful fix for https://github.com/clj-kondo/clj-kondo/issues/1726 that solved an issue with calls to clojure.core/sequence with a transducer and multiple collections reporting invalid arity problems. That fix covers map-as-transducer, but doesn't work for mapcat.

### PR DESCRIPTION
**Pull request by chancerussell**
Gives mapcat the same special handling as map for situations where it's being used as a transducer inside sequence and thus can have its internal function called with arities above 1.

Fixes #1755.

- [x] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by chancerussell** [comment]
Please feel free to modify, mangle and/or merge this code as you like :) Thanks!

File: src/clj_kondo/impl/analyzer.clj [hunk 1]
```diff
@@ -1663,7 +1663,7 @@
         arg-count (if (and transducer-eligable?
                            (zero? arg-count)) ;; transducer
                     (if (and (= 'clojure.core hof-ns-name)
-                             (= 'map hof-resolved-name))
+                             (#{'map 'mapcat} hof-resolved-name))
```
Comment (borkdude) [inline src/clj_kondo/impl/analyzer.clj:1666]: Although probably not so important, I usually abstain from this style to keep performance optimal and write out:

```
(or (= 'map ...) (= 'mapcat ...))
```

**Comment by borkdude** [comment]
One minor comment, but looks good apart from that!

**Comment by borkdude** [comment]
Thanks!
