### PR TITLE
Lint bb.edn and deps.edn :paths for data type

### LINKED ISSUE #1353: Consider linting :paths value data type in bb.edn and deps.edn
### Problem
On more than one occasion I have included the following in my `bb.edn` file:
```Clojure
{:paths [script]
```
Although this is syntactically incorrect, babashka happens to parse it just fine. 
Other tools might not be so lenient or even crash. For example, it was [causing clojure-lsp to crash](https://github.com/clojure-lsp/clojure-lsp/issues/507).

The correct syntax is a vector of strings:
```Clojure
{:paths ["script"]
```

It would be helpful if clj-kondo warned when the data type is incorrect for `:paths`.

### Additional context
There is an existing [`:deps.edn` linter](https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#depsedn) which already does some data type checking, ex. for 
```Clojure
{:deps {foo/bar "2020.10.11"}}
``` 
clj-kondo reports:
```shell
deps.edn:1:18: warning: Expected map, found: java.lang.String
```
(Aside: this particular check does not seem to currently apply to `bb.edn`)

### Proposed Solution

Follow existing `:deps.edn` linter (see above) convention and show "Expected &lt;data type x&gt;, found: &lt;data type y&gt;." In this specific case:
`expected java.lang.String, found symbol`
or maybe:
`expected string, found symbol`

### Questions
Should we bundle`bb.edn` checking into the existing `:deps.edn` linter? Or should we create a new `:bb.edn` linter?

Should we expand scope of this issue?:
- in addition to checking for string, also check that `:paths` specifies a vector?
- lint data types of other elements in `bb.edn`?
- also likewise lint `:paths` in `deps.edn`? 
  - I do see a [spec](https://github.com/clojure/tools.deps.alpha/blob/9bf5778dc26dd5018dbf04fc8e7dbb32ddc4036c/src/main/clojure/clojure/tools/deps/alpha/specs.clj) for it
  - Note that in `deps.edn`, `:paths` can be strings or keywords (aliases).

###  Action
There are open questions, if it makes sense, we can move a GitHub discussion and I can come back and edit this issue with the outcome.
After we agree on what we want to do, I can follow up with  a PR.

### PR DESCRIPTION
**Pull request by lread**
We recognize that deps.edn and bb.edn differ slightly in what elem types
they support for :paths.
- deps.edn - strings or keywords
- bb.edn - strings onlys

When reporting on data type errors, I've favoured generic English words
over specific class names. For example instead of:

 Expected vector, found: clojure.lang.PersistentHashMap

We report:

 Expected vector, found: map

Closes #1353

### CODE REVIEW

**Comment by lread** [comment]
Lemme know what you think, happy to make any changes you feel are needed.  
I felt that my code might be a bit on the wordy side for this one, but I think it is pretty clear what it does.

Output from `script/diff` for this PR:
```Shell
❯ script/diff
Linting and writing output to /tmp/clj-kondo-diff/branch.txt
Cloning into 'clj-kondo'...
remote: Enumerating objects: 12375, done.
remote: Counting objects: 100% (1399/1399), done.
remote: Compressing objects: 100% (599/599), done.
remote: Total 12375 (delta 764), reused 1175 (delta 695), pack-reused 10976
Receiving objects: 100% (12375/12375), 11.82 MiB | 8.30 MiB/s, done.
Resolving deltas: 100% (7145/7145), done.
Linting and writing output to /tmp/clj-kondo-diff/master.txt
2558c2558
< linting took 11641ms, errors: 264, warnings: 2293
---
> linting took 11603ms, errors: 264, warnings: 2293
```

File: src/clj_kondo/impl/analyzer.clj [hunk 1]
```diff
@@ -2178,8 +2178,10 @@
           ;; analyze-expressions should go first in order to process ignores
           (when (identical? :edn lang)
             (let [fn (.getName (io/file filename))]
-              (when (= fn "deps.edn")
-                (deps-edn/lint-deps-edn ctx (first (:children parsed)))))))))
+              (condp = fn
```
Comment (borkdude) [inline src/clj_kondo/impl/analyzer.clj:2181]: why not just use case here?

**Comment by borkdude** [comment]
Thanks, I'll take a look tomorrow.

File: src/clj_kondo/impl/analyzer.clj (hunk 1 above)
Comment (lread) [reply src/clj_kondo/impl/analyzer.clj:2181]: Ya, I dunno, I started with a case and somehow ended up with a condp.  
Will change to case.
