### PR TITLE
Fix regression for unused binding warnings

### LINKED ISSUE #2713: Regression in v2025.12.23: Getting `unused binding` warning in `~'~` unquote expressions
- [x] I have read the [Clojure etiquette](https://clojure.org/community/etiquette) and will respect it when communicating on this platform.

**version**

v2025.12.23

**macro usage**

Not on macro usage but on macro definitions.

**platform**

Native version on macOS (`Mach-O 64-bit executable arm64`) as well as the Linux version provided in https://hub.docker.com/layers/cljkondo/clj-kondo/latest/images/sha256-71de5639d865100db82b7739adce96450bc5e0c9c552ed0df259391fed68cc3b

**problem**

When unquoting a symbol via `~'~` which typically appear in nested backquote expressions (e.g. when defining macro defining macros or functions), the unquoted symbol is not recognized as a used binding anymore. This wasn't an issue before v2025.12.23.

**repro**

E.g. try 

```clojure
(defmacro evaluator [expr]
  `(fn [& args#]
     (eval `(~'~expr ~@args#))))
```

from [ninety-nine-clojure/src/ninety_nine_clojure](https://github.com/pebrc/ninety-nine-clojure/blob/4aec31b42bd47509c3ef3d1b874eb1f5c1172f54/src/ninety_nine_clojure/logic.clj#L33-L35)
which yields `warning: unused binding expr`. But you could find many more examples at https://github.com/search?q=%22~%27~%22+language%3AClojure+&type=code.

**expected behavior**

No warning should be issued when the binding is used in a nested unquoted expression.

### PR DESCRIPTION
**Pull request by jramosg**
Corrected the handling of unused binding warnings for symbols used in quote-unquote expressions. This change ensures that bindings within macros are accurately tracked, preventing false positives in linting results.

Fixes #2713 - Regression in v2025.12.23: Getting `unused binding` warning in `~'~` unquote expressions 

Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [Clojure etiquette](https://clojure.org/community/etiquette) and will respect it when communicating on this platform.

- [x] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

File: test/clj_kondo/bindings_test.clj [hunk 1]
```diff
@@ -245,7 +245,32 @@
   (is (empty? (lint! "(doto (Object.) (.method))"
                      '{:linters {:used-underscored-binding {:level :warning}}})))
   (is (empty? (lint! "(defmulti foo (fn [this x] x))"
-                     '{:linters {:unused-binding {:level :warning :exclude-patterns ["this"]}}}))))
+                     '{:linters {:unused-binding {:level :warning :exclude-patterns ["this"]}}})))
+  (testing "issue 2713: quote-unquote should register binding usage"
+    (is (empty? (lint! "(defmacro evaluator [expr]
```
Comment (borkdude) [inline test/clj_kondo/bindings_test.clj:250]: This test didn't give a false positive before your PR. The case reported was this:

```
(defmacro evaluator [expr]
  `(fn [& args#]
     (eval `(~'~expr ~@args#))))
 ```

**Comment by borkdude** [comment]
Thanks!
