### PR TITLE
Fix #2345: SARIF output fix and some enhancements

### LINKED ISSUE #2345: Invalid SARIF output
- [x] I have read the [Clojure etiquette](https://clojure.org/community/etiquette) and will respect it when communicating on this platform.

**Version - 2024.05.24**
 
 

**Problem**
 
The SARIF output generated by Clj-kondo does not conform to the schema specified [here](https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html).

Specifically, the `region` attribute in the `results` location is nested at an incorrect level. 

According to the specification the correct nesting of `region` is `results -> locations -> physicalLocation -> region`
Clj-kondo nests the `region` property under  `results  ->  locations  -> physicalLocation -> artifactLocation -> region`
 
 ---- 
 
**Repro**

We have `bad_clojure.clj`:

```clj
(ns bad-clojure
  (:require
   [clojure.test :refer :all]
   [clojure.string :as str]))

(defn- foo [bar] nil)
```

If we run `clj-kondo --lint bad_clojure.clj --config '{:output {:format :sarif}}'` we get this output -

<details>
  <summary>Output (Click to expand)</summary>

```json 

{
  "version": "2.1.0",
  "$schema": "http://json.schemastore.org/sarif-2.1.0-rtm.4",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "Clj-kondo",
          "informationUri": "https://github.com/clj-kondo/clj-kondo",
          "rules": [
            {
              "id": "hook"
            },
            {
              "id": "docstring-leading-trailing-whitespace"
            },
            {
              "id": "bb.edn-cyclic-task-dependency"
            },
            {
              "id": "case-quoted-test"
            },
            {
              "id": "datalog-syntax"
            },
            {
              "id": "redundant-do"
            },
            {
              "id": "plus-one"
            },
            {
              "id": "conflicting-fn-arity"
            },
            {
              "id": "redundant-fn-wrapper"
            },
            {
              "id": "type-mismatch"
            },
            {
              "id": "docstring-blank"
            },
            {
              "id": "keyword-binding"
            },
            {
              "id": "protocol-method-varargs"
            },
            {
              "id": "format"
            },
            {
              "id": "deps.edn"
            },
            {
              "id": "underscore-in-namespace"
            },
            {
              "id": "clj-kondo-config"
            },
            {
              "id": "condition-always-true"
            },
            {
              "id": "redundant-let"
            },
            {
              "id": "misplaced-docstring"
            },
            {
              "id": "discouraged-tag"
            },
            {
              "id": "equals-true"
            },
            {
              "id": "consistent-alias"
            },
            {
              "id": "non-arg-vec-return-type-hint"
            },
            {
              "id": "missing-test-assertion"
            },
            {
              "id": "aliased-namespace-symbol"
            },
            {
              "id": "line-length"
            },
            {
              "id": "use"
            },
            {
              "id": "unused-referred-var"
            },
            {
              "id": "equals-false"
            },
            {
              "id": "duplicate-set-key"
            },
            {
              "id": "duplicate-map-key"
            },
            {
              "id": "bb.edn-unexpected-key"
            },
            {
              "id": "not-empty?"
            },
            {
              "id": "file"
            },
            {
              "id": "def-fn"
            },
            {
              "id": "unknown-require-option"
            },
            {
              "id": "missing-clause-in-try"
            },
            {
              "id": "discouraged-namespace"
            },
            {
              "id": "refer-all"
            },
            {
              "id": "inline-def"
            },
            {
              "id": "missing-body-in-when"
            },
            {
              "id": "deprecated-namespace"
            },
            {
              "id": "unresolved-symbol"
            },
            {
              "id": "cond-else"
            },
            {
              "id": "unsorted-required-namespaces"
            },
            {
              "id": "missing-docstring"
            },
            {
              "id": "conflicting-alias"
            },
            {
              "id": "single-operand-comparison"
            },
            {
              "id": "minus-one"
            },
            {
              "id": "bb.edn-task-missing-docstring"
            },
            {
              "id": "missing-else-branch"
            },
            {
              "id": "loop-without-recur"
            },
            {
              "id": "namespace-name-mismatch"
            },
            {
              "id": "unused-import"
            },
            {
              "id": "discouraged-var"
            },
            {
              "id": "shadowed-var"
            },
            {
              "id": "var-same-name-except-case"
            },
            {
              "id": "unexpected-recur"
            },
            {
              "id": "self-requiring-namespace"
            },
            {
              "id": "deprecated-var"
            },
            {
              "id": "earmuffed-var-not-dynamic"
            },
            {
              "id": "unbound-destructuring-default"
            },
            {
              "id": "equals-expected-position"
            },
            {
              "id": "dynamic-var-not-earmuffed"
            },
            {
              "id": "redundant-expression"
            },
            {
              "id": "multiple-async-in-deftest"
            },
            {
              "id": "case-duplicate-test"
            },
            {
              "id": "aliased-namespace-var-usage"
            },
            {
              "id": "syntax"
            },
            {
              "id": "single-key-in"
            },
            {
              "id": "unused-value"
            },
            {
              "id": "used-underscored-binding"
            },
            {
              "id": "redundant-call"
            },
            {
              "id": "unused-namespace"
            },
            {
              "id": "java-static-field-call"
            },
            {
              "id": "case-symbol-test"
            },
            {
              "id": "unused-alias"
            },
            {
              "id": "reduce-without-init"
            },
            {
              "id": "private-call"
            },
            {
              "id": "unresolved-var"
            },
            {
              "id": "unsorted-imports"
            },
            {
              "id": "duplicate-field"
            },
            {
              "id": "not-a-function"
            },
            {
              "id": "duplicate-require"
            },
            {
              "id": "unused-private-var"
            },
            {
              "id": "docstring-no-summary"
            },
            {
              "id": "unresolved-namespace"
            },
            {
              "id": "uninitialized-var"
            },
            {
              "id": "main-without-gen-class"
            },
            {
              "id": "invalid-arity"
            },
            {
              "id": "single-logical-operand"
            },
            {
              "id": "shadowed-fn-param"
            },
            {
              "id": "warn-on-reflection"
            },
            {
              "id": "bb.edn-undefined-task"
            },
            {
              "id": "missing-map-value"
            },
            {
              "id": "unreachable-code"
            },
            {
              "id": "refer"
            },
            {
              "id": "redefined-var"
            },
            {
              "id": "unused-binding"
            },
            {
              "id": "redundant-str-call"
            }
          ]
        }
      },
      "artifacts": [
        {
          "location": {
            "uri": "bad_clojure.clj"
          }
        }
      ],
      "results": [
        {
          "level": "warning",
          "message": {
            "text": "namespace clojure.string is required but never used"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "bad_clojure.clj",
                  "index": 0,
                  "region": {
                    "startLine": 2,
                    "startColumn": 14
                  }
                }
              }
            }
          ],
          "ruleId": "unused-namespace",
          "ruleIndex": 74
        },
        {
          "level": "warning",
          "message": {
            "text": "use alias or :refer"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "bad_clojure.clj",
                  "index": 0,
                  "region": {
                    "startLine": 3,
                    "startColumn": 34
                  }
                }
              }
            }
          ],
          "ruleId": "refer-all",
          "ruleIndex": 39
        },
        {
          "level": "warning",
          "message": {
            "text": "Unused private var bad-clojure/foo"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "bad_clojure.clj",
                  "index": 0,
                  "region": {
                    "startLine": 5,
                    "startColumn": 8
                  }
                }
              }
            }
          ],
          "ruleId": "unused-private-var",
          "ruleIndex": 85
        },
        {
          "level": "warning",
          "message": {
            "text": "unused binding bar"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "bad_clojure.clj",
                  "index": 0,
                  "region": {
                    "startLine": 5,
                    "startColumn": 13
                  }
                }
              }
            }
          ],
          "ruleId": "unused-binding",
          "ruleIndex": 99
        }
      ]
    }
  ]
}

```
  </details>
  
This output is invalid and can be validated [here](https://sarifweb.azurewebsites.net/Validation).

----
 
**Expected behavior**

The SARIF output would conform to the specification. 

I can submit a PR that fixes this issue.

### PR DESCRIPTION
**Pull request by nxvipin**
Issue #2345

- Fix the nesting level of `region` under the `results` property

- Enhance SARIF output
  - Add Clj-kondo `version` to the SARIF output
  - Add `endLine` and `endColumn` to the linting results
  - Add `helpUri`, `level` and `enabled` to the linting rules
  - Remove `artifacts` key as it did not contain any additonal data
    from what is available under the results key.
    (This is based on the suggestion of the SARIF [validator](https://sarifweb.azurewebsites.net/Validation))
    
-----

### Test code with lint issues

```clojure
(ns bad-clojure
  (:require
   [clojure.test :refer :all]
   [clojure.string :as str]))

(defn- foo [bar] nil)

```    

<details>
<summary> SARIF output</summary>

```json
 
{
  "version": "2.1.0",
  "$schema": "https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/schemas/sarif-schema-2.1.0.json",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "Clj-kondo",
          "version": "2024.05.25-SNAPSHOT",
          "informationUri": "https://github.com/clj-kondo/clj-kondo",
          "rules": [
            {
              "id": "hook",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#hook",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "docstring-leading-trailing-whitespace",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#docstring-leading-trailing-whitespace",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "bb.edn-cyclic-task-dependency",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#bb.edn-cyclic-task-dependency",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "case-quoted-test",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#case-quoted-test",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "datalog-syntax",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#datalog-syntax",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "redundant-do",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#redundant-do",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "plus-one",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#plus-one",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "conflicting-fn-arity",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#conflicting-fn-arity",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "redundant-fn-wrapper",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#redundant-fn-wrapper",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "type-mismatch",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#type-mismatch",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "docstring-blank",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#docstring-blank",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "keyword-binding",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#keyword-binding",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "protocol-method-varargs",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#protocol-method-varargs",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "format",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#format",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "deps.edn",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#deps.edn",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "underscore-in-namespace",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#underscore-in-namespace",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "clj-kondo-config",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#clj-kondo-config",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "condition-always-true",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#condition-always-true",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "redundant-let",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#redundant-let",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "misplaced-docstring",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#misplaced-docstring",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "discouraged-tag",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#discouraged-tag",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "equals-true",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#equals-true",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "consistent-alias",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#consistent-alias",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "non-arg-vec-return-type-hint",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#non-arg-vec-return-type-hint",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "missing-test-assertion",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#missing-test-assertion",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "aliased-namespace-symbol",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#aliased-namespace-symbol",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "line-length",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#line-length",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "use",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#use",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "unused-referred-var",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unused-referred-var",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "equals-false",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#equals-false",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "duplicate-set-key",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#duplicate-set-key",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "duplicate-map-key",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#duplicate-map-key",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "bb.edn-unexpected-key",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#bb.edn-unexpected-key",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "not-empty?",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#not-empty?",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "file",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#file",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "def-fn",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#def-fn",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "unknown-require-option",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unknown-require-option",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "missing-clause-in-try",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#missing-clause-in-try",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "discouraged-namespace",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#discouraged-namespace",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "refer-all",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#refer-all",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "inline-def",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#inline-def",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "missing-body-in-when",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#missing-body-in-when",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "deprecated-namespace",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#deprecated-namespace",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "unresolved-symbol",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unresolved-symbol",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "cond-else",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#cond-else",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "unsorted-required-namespaces",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unsorted-required-namespaces",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "missing-docstring",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#missing-docstring",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "conflicting-alias",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#conflicting-alias",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "single-operand-comparison",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#single-operand-comparison",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "minus-one",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#minus-one",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "bb.edn-task-missing-docstring",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#bb.edn-task-missing-docstring",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "missing-else-branch",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#missing-else-branch",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "loop-without-recur",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#loop-without-recur",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "namespace-name-mismatch",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#namespace-name-mismatch",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "unused-import",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unused-import",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "discouraged-var",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#discouraged-var",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "shadowed-var",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#shadowed-var",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "var-same-name-except-case",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#var-same-name-except-case",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "unexpected-recur",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unexpected-recur",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "self-requiring-namespace",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#self-requiring-namespace",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "deprecated-var",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#deprecated-var",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "earmuffed-var-not-dynamic",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#earmuffed-var-not-dynamic",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "unbound-destructuring-default",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unbound-destructuring-default",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "equals-expected-position",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#equals-expected-position",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "dynamic-var-not-earmuffed",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#dynamic-var-not-earmuffed",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "redundant-expression",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#redundant-expression",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "multiple-async-in-deftest",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#multiple-async-in-deftest",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "case-duplicate-test",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#case-duplicate-test",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "aliased-namespace-var-usage",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#aliased-namespace-var-usage",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "syntax",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#syntax",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "single-key-in",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#single-key-in",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "unused-value",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unused-value",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "used-underscored-binding",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#used-underscored-binding",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "redundant-call",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#redundant-call",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "unused-namespace",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unused-namespace",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "java-static-field-call",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#java-static-field-call",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "case-symbol-test",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#case-symbol-test",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "unused-alias",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unused-alias",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "reduce-without-init",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#reduce-without-init",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "private-call",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#private-call",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "unresolved-var",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unresolved-var",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "unsorted-imports",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unsorted-imports",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "duplicate-field",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#duplicate-field",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "not-a-function",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#not-a-function",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "duplicate-require",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#duplicate-require",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "unused-private-var",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unused-private-var",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "docstring-no-summary",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#docstring-no-summary",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "unresolved-namespace",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unresolved-namespace",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "uninitialized-var",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#uninitialized-var",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "main-without-gen-class",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#main-without-gen-class",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "invalid-arity",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#invalid-arity",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "single-logical-operand",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#single-logical-operand",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "shadowed-fn-param",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#shadowed-fn-param",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "warn-on-reflection",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#warn-on-reflection",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "bb.edn-undefined-task",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#bb.edn-undefined-task",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "missing-map-value",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#missing-map-value",
              "defaultConfiguration": {
                "enabled": true,
                "level": "error"
              }
            },
            {
              "id": "unreachable-code",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unreachable-code",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "refer",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#refer",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            },
            {
              "id": "redefined-var",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#redefined-var",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "unused-binding",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#unused-binding",
              "defaultConfiguration": {
                "enabled": true,
                "level": "warning"
              }
            },
            {
              "id": "redundant-str-call",
              "helpUri": "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#redundant-str-call",
              "defaultConfiguration": {
                "enabled": false,
                "level": "none"
              }
            }
          ]
        }
      },
      "results": [
        {
          "level": "warning",
          "message": {
            "text": "namespace clojure.string is required but never used"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "bad-src/bad_clojure.clj"
                },
                "region": {
                  "startLine": 2,
                  "startColumn": 14,
                  "endLine": 2,
                  "endColumn": 28
                }
              }
            }
          ],
          "ruleId": "unused-namespace"
        },
        {
          "level": "warning",
          "message": {
            "text": "use alias or :refer"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "bad-src/bad_clojure.clj"
                },
                "region": {
                  "startLine": 3,
                  "startColumn": 34,
                  "endLine": 3,
                  "endColumn": 38
                }
              }
            }
          ],
          "ruleId": "refer-all"
        },
        {
          "level": "warning",
          "message": {
            "text": "Unused private var bad-clojure/foo"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "bad-src/bad_clojure.clj"
                },
                "region": {
                  "startLine": 5,
                  "startColumn": 8,
                  "endLine": 5,
                  "endColumn": 11
                }
              }
            }
          ],
          "ruleId": "unused-private-var"
        },
        {
          "level": "warning",
          "message": {
            "text": "unused binding bar"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "bad-src/bad_clojure.clj"
                },
                "region": {
                  "startLine": 5,
                  "startColumn": 13,
                  "endLine": 5,
                  "endColumn": 16
                }
              }
            }
          ],
          "ruleId": "unused-binding"
        }
      ]
    }
  ]
}
```

</details>

The output is validated with the validator [here](https://sarifweb.azurewebsites.net/Validation) and there are zero errors and warnings. 
    
 ----

Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [Clojure etiquette](https://clojure.org/community/etiquette) and will respect it when communicating on this platform.

- [x] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [ ] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

File: src/clj_kondo/impl/sarif.clj [hunk 1]
```diff
@@ -1,36 +1,48 @@
...
-(defn finding->sarif [rules files finding]
-  {:level (:level finding)
+(defn- linter-help-uri [linter]
+  (format "https://github.com/clj-kondo/clj-kondo/blob/master/doc/linters.md#%s" (name linter)))
+
+(defn- sarif-level [level]
+  (case level
+    :error "error"
+    :warning "warning"
+    :off "none"))
```
Comment (borkdude) [inline src/clj_kondo/impl/sarif.clj:17]: clj-kondo also supports :info level, this function will crash currently if that level is used somewhere

**Comment by borkdude** [comment]
Thanks for the PR!
Perhaps this is also a good time to add a test, what do you think?

File: src/clj_kondo/impl/sarif.clj (hunk 1 above)
Comment (nxvipin) [reply src/clj_kondo/impl/sarif.clj:18]: Add :info level

**Comment by nxvipin** [comment]
@borkdude yes, I wanted to bring this up. I was looking for some existing tests that but looks like there aren't any. A clojure test for this would entail validating the SARIF output against the json schema defined in the spec using some third party json schema library included as a test dep. Did you have any thoughts on testing this? I can take a stab at this but this might take a few days.

**Comment by borkdude** [comment]
Maybe we could just add some more basic tests, given some input to `(clj-kondo.core/run! {:lint ["src"] :output {:format :sarif}})` and then ran through `clj-kondo.core/print!`, we can parse the resulting XML (and convert it back to a Clojure data structure maybe) and make some assertions on the parsed XML

**Comment by borkdude** [comment]
I can add a basic test in another PR first if you prefer that

**Comment by nxvipin** [comment]
@borkdude sounds good. I can add to it if needed. Thanks!

**Comment by borkdude** [comment]
I added a minimal sarif test on master now. Feel free to adapt it to your needs.

**Comment by borkdude** [comment]
Looks like I made the test successfully fail on your PR. The next step would be to make the test pass and then we can merge it.

**Comment by nxvipin** [comment]
@borkdude thank you! I have updated the tests.

**Comment by borkdude** [comment]
Excellent!
